apply plugin: 'com.android.application'

android {

    namespace "net.nyx.printerclient"
    compileSdk 36

    defaultConfig {
        applicationId "net.nyx.printerclient"
        minSdk  21
        targetSdk 36
        versionCode 1
        versionName "1.0.8"
    }

    signingConfigs {
        release {
            keyAlias 'nyx_demo'
            keyPassword '111111'
            storeFile file('../key/demo.jks')
            storePassword '111111'
        }
    }

    buildTypes {
        release {
            debuggable false
            jniDebuggable false
            zipAlignEnabled true
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }
    buildFeatures {
        aidl true
    }

    lintOptions {
        disable 'HardcodedText'
        disable 'ContentDescription'
    }


    applicationVariants.all { variant ->
        if (variant.buildType.name != "debug") {
            variant.getPackageApplicationProvider().get().outputDirectory = new File(project.rootDir.absolutePath + "/apk")
        }
        variant.outputs.all { output ->
            outputFileName = "${((project.name != "app") ? project.name : rootProject.name)}" +
                    "-${variant.buildType.name}" +
                    "_v${variant.versionName}" +
                    "_${new Date().format("yyyy-MM-dd")}" +
                    ".apk"
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.6.1'
    // https://github.com/JakeWharton/timber
    implementation 'com.jakewharton.timber:timber:4.7.1'
    // https://github.com/zxing/zxing
    implementation 'com.google.zxing:core:3.5.4'
}
